apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "nais-analyse-prod-2dcc"
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
  name: aivencost
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  friendlyName: aivencost
  location: europe-north1
  resourceID: aivencost

---

apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "nais-analyse-prod-2dcc"
  name: costitems
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  resourceID: costitems
  datasetRef:
    name: aivencost
  friendlyName: costitems
  schema: |
    [
      {
        "name": "invoiceId",
        "type": "STRING"
      },
      {
        "name": "environment",
        "type": "STRING"
      },
      {
        "name": "team",
        "type": "STRING"
      },
      {
        "name": "month",
        "type": "STRING"
      },
      {
        "name": "service",
        "type": "STRING"
      },
      {
        "name": "costInEuros",
        "type": "NUMERIC"
      }
    ]

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "nais-analyse-prod-2dcc"
  name: aiven-cost-dataset-editor
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  member: serviceAccount:aiven-cost-nais-analy-pbh2c4a@nais-prod-020f.iam.gserviceaccount.com
  role: roles/bigquery.dataEditor
  resourceRef:
    apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
    kind: BigQueryDataSet
    external: projects/nais-analyse-2dcc/datasets/aivencost

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "nais-analyse-prod-2dcc"
  name: aiven-cost-data-editor
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  member: serviceAccount:aiven-cost-nais-analy-pbh2c4a@nais-prod-020f.iam.gserviceaccount.com
  role: roles/bigquery.dataEditor
  resourceRef:
    apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
    kind: BigQueryTable
    external: projects/nais-analyse-2dcc/datasets/aivencost/tables/costitems