apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
  name: aivencost
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  friendlyName: aivencost
  location: europe-north1

---

apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: costitems
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  datasetRef:
    name: aivencost
  friendlyName: costitems
  schema: |
    [
      {
        "name": "invoiceId",
        "type": "STRING"
      },
      {
        "name": "environment",
        "type": "STRING"
      },
      {
        "name": "team",
        "type": "STRING"
      },
      {
        "name": "month",
        "type": "STRING"
      },
      {
        "name": "service",
        "type": "STRING"
      },
      {
        "name": "costInEuros",
        "type": "NUMERIC"
      }
    ]