apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
  name: aiven_cost
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  friendlyName: aiven_cost
  location: europe-north1

---

apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: aiven_cost
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  datasetRef:
    name: aiven_cost
  friendlyName: aiven_cost
  schema: |
    [
      {
        "name": "environment",
        "type": "STRING"
      },
      {
        "name": "application",
        "type": "STRING"
      },
      {
        "name": "version",
        "type": "STRING"
      },
      {
        "name": "deployer",
        "type": "STRING"
      },
      {
        "name": "deployed_timestamp",
        "type": "TIMESTAMP"
      },
      {
        "name": "replaced_timestamp",
        "type": "TIMESTAMP"
      },
      {
        "name": "environmentClass",
        "type": "STRING"
      },
      {
        "name": "id",
        "type": "STRING"
      }
    ]