apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "false"
  name: aiven-cost
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  friendlyName: aiven-cost
  location: europe-north1

---

apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: cost-items
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  description: "Aiven Cost"
  datasetRef:
    name: aiven-cost
  friendlyName: cost-items
  schema: |
    [
      {
        "name": "environment",
        "type": "STRING"
      },
      {
        "name": "team",
        "type": "STRING"
      },
      {
        "name": "month",
        "type": "STRING"
      },
      {
        "name": "service",
        "type": "STRING"
      },
      {
        "name": "costInEuros",
        "type": "NUMERIC"
      }
    ]