apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "aiven-cost"
  namespace: "nais-analyse"
  labels:
    "team": "nais-analyse"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  limits:
    cpu: "400m"
    memory: "1024Mi"
  requests:
    cpu: "200m"
    memory: "512Mi"
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}
  envFrom:
    - secret: aiven-token
  accessPolicy:
    outbound:
      external:
        - host: api.aiven.io